plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hoshino.companion'
    compileSdk 34

    defaultConfig {
        applicationId "com.hoshino.companion"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.1"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
